import { useState, useEffect } from "react";
import jwt_decode from "jwt-decode";
import HomeLayout from "../layouts/home-layout";
import Users from "../components/home/users";
import ChatSection from "../components/home/chat-section";
import { socketIO } from "../utils/socket-io";
import Head from "next/head";

export default function Home() {
  const [usersData, setUsersData] = useState([]);
  const [userInfo, setUserInfo] = useState();
  const [isActiveChat, setIsActiveChat] = useState(false);
  const [oppositID, setOppositeID] = useState();
  const [isPageReady, setIsPageReady] = useState(false);
  const socket = socketIO();
  useEffect(() => {
    const token = localStorage.getItem("token");
    const decoded = jwt_decode(token);
    setUserInfo(decoded);
    socket.emit("allUsers");
    socket.on("allUsersRes", (users) => {
      setUsersData(users);
    });
    setIsPageReady(true);
  }, []);
  const removeElement = (array, elem) => {
    let newData = [];
    array.map((item) => {
      if (item.userName != elem) newData.push(item);
    });

    return newData;
  };

  if (!isPageReady) return <div>loading...</div>;

  return (
    <HomeLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Users
        users={removeElement(usersData, userInfo?.userName)}
        userInfo={userInfo}
        setIsActiveChat={setIsActiveChat}
        setOppositeID={setOppositeID}
      />
      <ChatSection
        users={usersData}
        userInfo={userInfo}
        socket={socket}
        isActiveChat={isActiveChat}
        setIsActiveChat={setIsActiveChat}
        oppositID={oppositID}
      />
    </HomeLayout>
  );
}
